name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Check secrets
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "❌ RENDER_DEPLOY_HOOK_URL no está configurado"
            exit 1
          fi
          echo "✅ Secrets configurados correctamente"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: dependencias pnpm
        run: pnpm install

      - name: Install node
        uses: actions/setup-node@v4

      - name: dependencias
        run: npm install

      - name: Build TypeScript
        run: npm run build

      #- name: Run linter
      #  run: pnpm run lint

      #- name: Run tests
      #  run: npm test

      #- name: Run integration tests
      #  run: npm run test:integration

      - name: Deploy to render
        env:
          deploy_url: ${{  secrets.RENDER_DEPLOY_HOOK_URL  }}
        run: curl "$deploy_url"
